In [1]:
import numpy as np
wines = np.loadtxt("winequality-red (2).csv",delimiter=";",dtype="float",skiprows=1)

In [2]:
print(wines)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [3]:
np.shape(wines)

(1599, 12)

In [4]:
wines[3][4]

0.075

In [5]:
print(wines[:3,4])

[0.076 0.098 0.092]


In [6]:
print(wines[:,3])

[1.9 2.6 2.3 ... 2.3 2.  3.6]


In [7]:
print(wines[4])

[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
  0.56    9.4     5.    ]


In [8]:
wines[2][6]=10

In [9]:
slice_new = wines[:,10]
print(slice_new)
slice_new[:] = 666
print(slice_new)

[ 9.4  9.8  9.8 ... 11.  10.2 11. ]
[666. 666. 666. ... 666. 666. 666.]


In [10]:
print(wines)

[[7.40e+00 7.00e-01 0.00e+00 ... 5.60e-01 6.66e+02 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.80e-01 6.66e+02 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.50e-01 6.66e+02 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 7.50e-01 6.66e+02 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 7.10e-01 6.66e+02 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.60e-01 6.66e+02 6.00e+00]]


In [11]:
print(wines.dtype)
wines=np.array(wines,dtype=int)

float64


In [12]:
print(wines)

[[  7   0   0 ...   0 666   5]
 [  7   0   0 ...   0 666   5]
 [  7   0   0 ...   0 666   5]
 ...
 [  6   0   0 ...   0 666   6]
 [  5   0   0 ...   0 666   5]
 [  6   0   0 ...   0 666   6]]


In [13]:
print(wines[:,-1])
wines[:,-1]=wines[:,-1]+10
print(wines[:,-1])

[5 5 5 ... 6 5 6]
[15 15 15 ... 16 15 16]


In [14]:
print(wines)

[[  7   0   0 ...   0 666  15]
 [  7   0   0 ...   0 666  15]
 [  7   0   0 ...   0 666  15]
 ...
 [  6   0   0 ...   0 666  16]
 [  5   0   0 ...   0 666  15]
 [  6   0   0 ...   0 666  16]]


In [15]:
print(np.sum(wines))
print(sum(sum(wines)))

1210450
1210450


In [16]:
print(sum(wines))
print(sum(wines[:,-1]))
print(np.sum(wines,axis=1))

[  12589      24       1    3350       0   25382   74257      81    4770
      60 1064934   25002]
25002
[737 785 718 ... 762 767 754]


In [18]:
np.insert(wines,-1,wines[:,-1],axis=1)

array([[  7,   0,   0, ..., 666,  15,  15],
       [  7,   0,   0, ..., 666,  15,  15],
       [  7,   0,   0, ..., 666,  15,  15],
       ...,
       [  6,   0,   0, ..., 666,  16,  16],
       [  5,   0,   0, ..., 666,  15,  15],
       [  6,   0,   0, ..., 666,  16,  16]])

In [19]:
print(wines[:,-2])
print(wines[:,-1])
a=wines[:,-2]*wines[:,-1]
print(a)

[666 666 666 ... 666 666 666]
[15 15 15 ... 16 15 16]
[ 9990  9990  9990 ... 10656  9990 10656]


In [39]:
a=wines[:,-1]>5
print(a)
print(wines[:,-1][a])

[ True  True  True ...  True  True  True]
[15 15 15 ... 16 15 16]


In [43]:
len(wines[np.where(wines[:,-1]>5)])

1599

In [21]:
b=wines[:,-1]==10
print(wines[:,-1][b])

[]


In [22]:
a=wines[:,-1]>15
print(wines[:,-1])

[15 15 15 ... 16 15 16]


In [23]:
a=wines[:,-1]>7
print(wines[:,-1][a])

[15 15 15 ... 16 15 16]


In [24]:
a=wines[:,-1]>7
b=wines[:,-3]>10
print(b[a])
print(wines[:,-3])

[False False False ... False False False]
[0 0 0 ... 0 0 0]


In [37]:
print(wines)
a=np.reshape(wines,(533,36))
print(a.shape)
print(a)

[[  7   0   0 ...   0 666  15]
 [  7   0   0 ...   0 666  15]
 [  7   0   0 ...   0 666  15]
 ...
 [  6   0   0 ...   0 666  16]
 [  5   0   0 ...   0 666  15]
 [  6   0   0 ...   0 666  16]]
(533, 36)
[[  7   0   0 ...   0 666  15]
 [ 11   0   0 ...   0 666  15]
 [  7   0   0 ...   0 666  17]
 ...
 [  6   0   0 ...   0 666  16]
 [  6   0   0 ...   0 666  16]
 [  6   0   0 ...   0 666  16]]
